### ISSUE TITLE
Design + Build out index.html

### ISSUE THREAD

**Issue by mepda** [LearnTeachCodeSeoul/LearnTeachCodeSeoul.github.io#5]
I think the next task should be to design the website's landing page. We figured out last night about what we want in it at first being:
* **About page**
1. Facebook link
2. Meetup link
3. Slack link
* **Tutorials page**
1. Embedded or linked videos
2. Link to Beege's github
* **Schedule**
1. Maybe scraped from meetup?

**Comment by TheBeege** [comment]
I did the tutorials and schedule pages. 

I took a first pass at the About page... I put some of the stuff on the Index. Thoughts?

#10

**Comment by DaleSeo** [comment]
@TheBeege Good job!
