### ISSUE TITLE
add some links on about.html

### ISSUE THREAD

**Issue by DaleSeo** [LearnTeachCodeSeoul/LearnTeachCodeSeoul.github.io#8]
@mepda How about you try this one?

**Comment by mepda** [comment]
on it!~

**Comment by mepda** [comment]
alrighty, just added a bunch of links for coding stuff.

**Comment by mepda** [comment]
so, I ran into an error when I tried to push my "about" branch. Said the `current branch about has no upstream branch.` so I followed the suggestion for `git push --set-upstream origin about`. Just noting this here so I don't forget, and also maybe you can explain it to me more later.
